server:
  port: 1759
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/localhost.p12
    key-store-password: pangloss
  tomcat:
    accesslog:
      # accesspattern
      enabled: true
    basedir: target/logs

spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api

