server:
  port: 1759
spring:
  profiles:
    active: safe
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api


---
#Never use poc profile in production guys !!!!
spring:
  profiles: poc