server:
  port: 1759
  # Fixme: remove it
  tomcat:
    accesslog:
      # accesspattern
      pattern: "%h %l %t userId: %{userId}s \"%r\" %s %b %D"
      enabled: true
    basedir: target/logs
    # Fixme: remove it
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/localhost.p12
    key-store-password: pangloss

spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api

