server:
  port: 1759
  tomcat:
    accesslog:
      # accesspattern
      enabled: true
    basedir: target/logs

spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api

