server:
  port: 1759
spring:
  profiles:
    active: safe, ssl
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api

---

spring:
  profiles: ssl

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/localhost.p12
    key-store-password: pangloss