server:
  port: 1759
  # Fixme: remove it
  tomcat:
    accesslog:
      enabled: true
    basedir: target/logs
  # ssl

spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    generate-unique-name: true
  data:
    rest:
      base-path: /api

